import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('api', {
    db: {
        getProducts: () => ipcRenderer.invoke('db:getProducts'),
        getProductByBarcode: (barcode: string) => ipcRenderer.invoke('db:getProductByBarcode', barcode),
        searchProducts: (query: string) => ipcRenderer.invoke('db:searchProducts', query),
        saveProduct: (data: any) => ipcRenderer.invoke('db:saveProduct', data),
        deleteProduct: (id: number) => ipcRenderer.invoke('db:deleteProduct', id),
        getCategories: () => ipcRenderer.invoke('db:getCategories'),
        addCategory: (nombre: string) => ipcRenderer.invoke('db:addCategory', nombre),
        getSessionStatus: () => ipcRenderer.invoke('db:getSessionStatus'),
        openCaja: (monto: number) => ipcRenderer.invoke('db:openCaja', monto),
        closeCaja: (data: any) => ipcRenderer.invoke('db:closeCaja', data),
        getCajaActual: (sessionId: number) => ipcRenderer.invoke('db:getCajaActual', sessionId),
        getSalesForSession: (sessionId: number) => ipcRenderer.invoke('db:getSalesForSession', sessionId),
        getSaleDetails: (ventaId: number) => ipcRenderer.invoke('db:getSaleDetails', ventaId),
        createSale: (data: any) => ipcRenderer.invoke('db:createSale', data),
        getReportDetail: () => ipcRenderer.invoke('db:getReportDetail'),
        getReportMonthly: () => ipcRenderer.invoke('db:getReportMonthly'),
        getLastClosingAmount: () => ipcRenderer.invoke('db:getLastClosingAmount'),
        getClients: () => ipcRenderer.invoke('db:getClients'),
        addClient: (data: any) => ipcRenderer.invoke('db:addClient', data),
        payClientDebt: (data: any) => ipcRenderer.invoke('db:payClientDebt', data),
        addClientDebt: (data: any) => ipcRenderer.invoke('db:addClientDebt', data),
        getClientSales: (clientId: number) => ipcRenderer.invoke('db:getClientSales', clientId),
        deleteClient: (id: number) => ipcRenderer.invoke('db:deleteClient', id),
        addMovimiento: (data: any) => ipcRenderer.invoke('db:addMovimiento', data),
        getMovimientos: (sessionId: number) => ipcRenderer.invoke('db:getMovimientos', sessionId),
        clearHistory: () => ipcRenderer.invoke('db:clearHistory'),
        getTotalesSugeridos: (sessionId: number) => ipcRenderer.invoke('db:getTotalesSugeridos', sessionId),
        getSuppliers: () => ipcRenderer.invoke('db:getSuppliers'),
        saveSupplier: (data: any) => ipcRenderer.invoke('db:saveSupplier', data),
        deleteSupplier: (id: number) => ipcRenderer.invoke('db:deleteSupplier', id),
        getSuppliersByProduct: (productId: number) => ipcRenderer.invoke('db:getSuppliersByProduct', productId),
        getProductsBySupplier: (supplierId: number) => ipcRenderer.invoke('db:getProductsBySupplier', supplierId),
        updateProductSuppliers: (data: { productId: number, supplierIds: number[] }) => ipcRenderer.invoke('db:updateProductSuppliers', data),
        getStatsResumen: (period: string) => ipcRenderer.invoke('db:getStatsResumen', period),
        getTopProductos: (period: string) => ipcRenderer.invoke('db:getTopProductos', period),
        getMenosVendidos: (period: string) => ipcRenderer.invoke('db:getMenosVendidos', period),
        getStatsMetodoPago: (period: string) => ipcRenderer.invoke('db:getStatsMetodoPago', period),
        getStatsCategorias: (period: string) => ipcRenderer.invoke('db:getStatsCategorias', period),
        getStatsHoraPico: (period: string) => ipcRenderer.invoke('db:getStatsHoraPico', period),
        getProductosBajoStock: (umbral?: number) => ipcRenderer.invoke('db:getProductosBajoStock', umbral),
    },
    barcode: {
        lookup: (barcode: string) => ipcRenderer.invoke('api:lookupBarcode', barcode),
    },
});
